export const GAME_STATUS_WAITING_FOR_PLAYERS = 'W';
export const GAME_STATUS_RUNNING = 'R';
export const GAME_STATUS_ENDED = 'E';

export const START_OPTION_NEW_GAME = 'NEW_GAME';
export const START_OPTION_ATTEND_GAME = 'ATTEND_GAME';
export const START_OPTION_RETURN_TO_GAME = 'RETURN_TO_GAME';
